### PR TITLE
PARQUET-1980 Add an info about Pull Requests' testing

### PR DESCRIPTION
**Pull request by martin-g**
* Add a line that PRs are automatically tested at GitHub Actions (for AMD64) and TravisCI (for ARM64).
* Replace the obsolete git-wip-us with gitbox
* minor Markdown improvements

### CODE REVIEW

**Review by gszadovszky — CHANGES_REQUESTED** [review]
Thanks a lot, @martin-g for this update.

Currently, we need to manually update the html files as well. See [README.md](https://github.com/apache/parquet-site#generating-the-website) for details.

**Comment by martin-g** [comment]
@gszadovszky Added it!

**Review by gszadovszky — APPROVED** [review]

**Comment by martin-g** [comment]
https://parquet.apache.org/contribute/ gives 404
Did I break it somehow ?

**Comment by gszadovszky** [comment]
This is strange. I've seen it working with your updates just after the commit. Now, the whole parquet site is down.

UPDATE: Seems to be working again

**Comment by martin-g** [comment]
The landind/index page is OK but any other gives 404:
- https://parquet.apache.org/documentation/latest/
- https://parquet.apache.org/downloads
- https://parquet.apache.org/presentations
- https://parquet.apache.org/adopters

**Comment by martin-g** [comment]
maybe `git commit --allow-empty -m "re-deploy the site"` will fix it ?!

**Comment by martin-g** [comment]
Sorry, it seems to have been a caching issue on my side.
All is good now!

**Comment by gszadovszky** [comment]
Don't know what it was but I've seen the same so it was not on your client side but some server issues.

**Pull request merged**
