### PR TITLE
Updating Staging

### PR DESCRIPTION
**Pull request by vinooganesh**
This PR does a few things:
1. Moves from the docsy git submodule to hugo modules
2. Pulls in the changes from `production` to bring staging up to the same point 
3. Updates the github actions versions 
4. Modes from `_index.html` -> `_index.md` for the site root
5. Updates the 404 page

### CODE REVIEW

**Comment by wgtmac** [comment]
IIUC, the staging site is no longer maintained. cc @gszadovszky @shangxinli

**Comment by vinooganesh** [comment]
Yeah haha @wgtmac, that's mostly me being negligent. I'm going to get everything up to date on both staging and production now

**Comment by vinooganesh** [comment]
@shangxinli can you +1 and merge? once it's good here, I'll make the change on prod

**Comment by shangxinli** [comment]
+1

**Comment by vinooganesh** [comment]
FYI in case someone finds this later, the URL of staging is https://parquet.staged.apache.org/

**Comment by wgtmac** [comment]
Is it possible to retire the staging site? It does not seem necessary to me.

**Comment by vinooganesh** [comment]
@wgtmac - that's a valid point. It's good for situations like this where we have to debug something strange before going to prod (https://github.com/apache/parquet-site/actions/runs/8149845126/job/22275151185). 

But, overall, it's pretty common for folks to have a staging site. For example: https://github.com/apache/dubbo-website/blob/master/.asf.yaml#L31. ASF docs have it as an option too: https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#staging.

**Comment by vinooganesh** [comment]
Ugh I think staging is hitting this: https://github.com/golang/go/issues/62278

```go: download go1.23 for linux/amd64: toolchain not available```

**Pull request merged**
