### PR TITLE
Add Parquet-Java 1.14.4

### PR DESCRIPTION
**Pull request by Fokko**
And replaced some Parquet-mr with Parquet-java

### CODE REVIEW

**Review by wgtmac — COMMENTED** [review]
1.14.4.md is not checked in?

**Comment by Fokko** [comment]
@wgtmac Oops, good one! Now it is: https://github.com/apache/parquet-site/pull/88/files#diff-0db57ae20f8555b94202ab8c0fa8de06ca6f2abb3efb09a34bd73636992ac149

**Review by wgtmac — APPROVED** [review]

**Comment by wgtmac** [comment]
Thanks @Fokko!

**Comment by Fokko** [comment]
@wgtmac Any time, thank you for the quick follow up!

**Pull request merged**
